---
when:
  - event: push
    branch: main

steps:
  - name: YAML Lint
    image: alpine:latest
    commands:
      - apk add yamllint
      - yamllint .

  - name: Ansible Lint
    image: alpine:latest
    commands:
      - apk add --no-cache ansible-lint git
      - cd ansible
      - yamllint .
      - ansible-lint
