---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pangolin-blueprints
  namespace: tekton-pipelines
spec:
  params:
    - name: revision
      type: string
      default: main
  tasks:
    - name: apply
      taskRef:
        name: pangolin-apply-blueprints
      params:
        - name: revision
          value: $(params.revision)
