---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Ensure hostname resolves locally
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\s'
    line: "127.0.1.1\t{{ inventory_hostname }}"

- name: Set timezone
  community.general.timezone:
    name: "{{ node_timezone }}"

- name: Install packages
  ansible.builtin.apt:
    name: "{{ node_base_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Enable iscsid for Longhorn
  ansible.builtin.systemd:
    name: iscsid
    state: started
    enabled: true

- name: Configure node
  ansible.builtin.include_tasks: "{{ include_item }}"
  loop:
    - swap.yml
    - network.yml
    - ssh.yml
  loop_control:
    loop_var: include_item
