---
kind: Service
apiVersion: v1
metadata:
  name: newt-paperless-service
  namespace: newt
spec:
  type: ExternalName
  externalName: paperless-ngx.paperless.svc.cluster.local
  ports:
    - port: 8000
