token: ENC[AES256_GCM,data:3FVSlbCj5gWAlLo+GfZw3HuKoQru0JhVZqnWTsPFAocffdhWeYc0RGoc85Z8DKT381rELZkHLEyKopQE/09mTw==,iv:yaWO1uxUNXDDt9VyX5SQjiBZd+DfszyBchNCUn9o7tA=,tag:hl/rZOfGgkg/Q6wmfcN0Bw==,type:str]
sops:
    lastmodified: "2026-09-05T17:51:36Z"
    mac: ENC[AES256_GCM,data:qXNY+bkrIFVXugeVJ3OzB443gVFGYw+mLjaEYtchV1WOSb2tmksqiW0DNL0JXeze89Es9ZKMMU8PaQYwFtuzYZP2L4lYhpqW73SIpgXaSie3juJob01AdrrINZnplqDmcCTVI19D0bS/W2RK4q04i/3N3Tb3K77hNY7+r9ddnG8=,iv:ZjrPT4SqGwV5fxHHSGwu+CDOz12Y3DvP4BEk5a7Okd8=,tag:xGg2Zx+C1+yqiW2vIV38/w==,type:str]
    pgp:
        - created_at: "2026-09-05T17:51:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPAQ//bVXyMZDIygfvCqXKPsm6sCRA3JChu9cuWwaZ6RqGIEr+
            4EY7SJJfzXx3YGJsIrqSFbGH3ufVSNygixh9lWXuOorNk0ow68RI2u1K2TGFODTM
            oGs/26r07EB4jdnQRO0CBEVSUjZ0gTC9RhFwdRcs/ZWzuZpKZYT21GPK9/Iw+7HZ
            7AskXx/48g1F5nKPATaoFfWfgisrrh731N/ieH/gHki9rXpmyHbBt3aCIBBsEKA2
            wQm4zyVQoLE1nfQ8hzjgBbD92dNw7Y4wBNlzDxSWdPV/dknzqXU0AGAK7mwfeEwc
            U763cF7ckBd9yhnox3UVOSB8I3zCtHIh3up1TZzwpTVOloryhk6jJCEydRlaVYcB
            8friiO28p820gJ2IN2OOueX8/5en8034E3dUg95Zq93x6Yhi8CLCb2YxecInRKtM
            wLGB/CGNTCBPNXSLO75R54fCQ21fpWKMkGYQlRlcYd357Lys2Rn/NS2xerjtvBCI
            ZAivEcbpCSJkYPRP9/s04uXnfZ4S5FPlrNhdIG6CUqevU2r1iSPXpPUZswgqDbU0
            ER03+8Kh51CuFeQPXwsAtMe6RyT4sg7Re7qQD5KoeBPW2ERqTojoB7hEQH1QWDCk
            7W+3b2f96Ts4IGXMOof308nDHv+5pjRqc8aWWYvl0dbR+Ws2JQumkSlppdP9ObrS
            XgFa6/xhyQrKj5+2ZF3G7eZd0cHm7iJyMDU9dZP92OQmFYAiKqodW2lL3qRIyfZW
            W5x8VPDct3G5ztpEd2xL36f0DYfzTg1NABRpZtN8pF6UvFO8a5nxqRCVNt9Rsls=
            =+v5n
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(token)$
    version: 3.11.0
