# Von scripts/secret.sh erzeugt. Anwenden mit:
#   sops -d secrets/arcane-secrets.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: arcane-secrets
    namespace: arcane
type: Opaque
stringData:
    oidc-client-secret: ENC[AES256_GCM,data:b7EHe+Kd1k2rV3oxmTQ/q8H4l3xb+dS9ejHJqVN9hr8=,iv:QebuY1I+FcJ35rmqhYqUTP8S9FPHTtw49kuOkKfLuaY=,tag:VVuYrHTokbUk1hAdR6tUjw==,type:str]
    jwt-secret: ENC[AES256_GCM,data:SJlRO2RZmyDUdR1/v9mIlRoATHkHJTPni47uZcAGdUs=,iv:yyFdp8S+HEjuijBgJx5TM0YRnOOgvxGjS14pdxPzxsI=,tag:r92HM2rvGMMlgXvLWFz2Pg==,type:str]
    encryption-key: ENC[AES256_GCM,data:3hOgeP4evPKq+sLpJiPpOxp3PXed959fLmXXtUua1yk=,iv:w/dSpE0UZNrZCM09SCsclN5IdAaKR+0u1J6qhsWaxMA=,tag:g7dvyNdc6pL7N/K5X5CV0Q==,type:str]
sops:
    lastmodified: "2026-10-01T23:11:24Z"
    mac: ENC[AES256_GCM,data:35YS5i6bwSeSDpLlGulB48pcPdAMOiPctUOSHweq4Cd9Qvh1L8lRsE3+xnQM9NAf1NeD41b12jq8YI6cxWP4b2Uoq6hg4oog4BWDBrvtY0MJfwFf2ivjlzXa7+OFj4uqNBJMT5su47oJvF0S/EYVI3DjDaLGiCZpz/HfPYfNX/Q=,iv:+en51IiPPz2CM+ViCYbSRuRoLCM0H3n9zr09bDaFj9Q=,tag:4rzTyrxxhING7sMp2MQyaA==,type:str]
    pgp:
        - created_at: "2026-10-01T23:11:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPAQ/+LF8v0KGUfR5y6AmSyfSSRiSu8bodJytcPW4pZPzgIprg
            QZkVEihM+jRFnUQMR7l46+BOIH0iuJPkLhMpuqvLei0pSAtIgBucMvhIMOvl09Vw
            PNhn4goOfavIMlxjaykVOkOwHg+4XvMQfa0U+qKsLSQiku17ymENnc3gP2usN6cx
            WQxy4YJSrA7VdK8I22C1YYo9yYXTzUM9pnbfXIzgGz9eEgm1NmjTfWj64wfyM3C+
            HI6ZwjLxoRrqEbLWDRqmDVsTrJ0S3CHthgzGuUSw6jgeVnIJzErGBG5xpRuOGkvs
            oN7rpjX6SfxeMMIWPmF4vcexrUdMXTMcYoR3WayVBBLtX9LRV0cjCETgLAJUq2Ns
            H+J68WN238EMnQjPCh+aSjKrF9KwqcCQAIpSW6l5J0b0TVhATLPsIDjN2hRu6seR
            x5Dy8Tk36Onm+F+TYB13MUoKJmWdVnJbQfSNn9x+YGcxXj+K75jIHWXLBxc7or4x
            m6qMgm3nHiMbXA1hmo8qQATZqwwbD/RaAsbgDL0FepRlpynv7Puhh5+3guxarbKK
            /EWkQYtT0FC8LVQc/v4i47G38zyqWFiai3q9b1/B+5VjM1YzB15UVncNQ/TFFcCd
            BuxZTv2biIUVzbSwU5wVKVC+GN7KchtfPksalHXM0xYb/qfB5eLLZLvloVRvHZ3S
            XgEPnxgOYFhPAT4dtwyT0hzpeZDqWzQ+wT2N/qwUS24Goiixnyoe+HUUzPzR+Gh0
            J6/kWLFDeSmtz8vVLDaGlDeWEzmc/lPyVAJaiPk61ITzUAg9GG27Hgo2VDJkuAA=
            =TF1z
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
