# Von Hand anwenden, nicht von ArgoCD verwaltet:
#   sops -d secrets/arcane-secrets.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: arcane-secrets
    namespace: arcane
type: Opaque
stringData:
    encryption-key: ENC[AES256_GCM,data:ruZSvyRFEpTqooFJuB6M390kQ56O9qLq78AtSLw1hXk=,iv:qOep1Tom7HKYbfIkr11qsclQTdJWRok3tEeuBSGm5D0=,tag:CktVMu7Mf7uFEVBZWNcUgg==,type:str]
    jwt-secret: ENC[AES256_GCM,data:3C/Nnd/g/pnErvTz5bf/IYojHk2sS1Z75cDCCGrTOsk=,iv:qXMGxK3Fsk5EcSibkyjzrlQx7Dwxbq9bfgBGbpudQj4=,tag:E/6yqf2f+gBpKuikM6Kv3A==,type:str]
sops:
    lastmodified: "2026-09-06T00:05:55Z"
    mac: ENC[AES256_GCM,data:1tZhEryOVD8WCUGemTkAoUfvJzHIAOwtKJQ7Rrl7SVZcOvRo0K72QnX+tn63Wnm0qyE/dxM43a14xGS3MV3f04pZDHGONlOE96a0t/VGm+AX1UuWDuonJNtW8lhl6JhQRfqHV/CdJbdIOnhUt9weI0nkM0iVjk7wcJHbOe3cnVQ=,iv:PEi4YGDxB0O67lHYqifmDhg1qprWWkByQezweScBKZQ=,tag:E8QL3Sl/g8g0Hs9iFz5TkQ==,type:str]
    pgp:
        - created_at: "2026-09-06T00:05:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPAQ//S4ZM88KtJW0eLKggXNeIxOKKcwfs0eNn8JhyFzs+ha+e
            JJ9qUQAuUGGuGny7VEyt3UuSaiqwSbbtjein70JiBftCEBNr1nYxkBQtjKQyrW2H
            CZS9UyxOEJlYB9X2kL1AIxYhmhR5MWlm5CT/CWpkgWc1auAZtwu18lielIg7jjqf
            5jx0oOcRlbBN3rYqxUHzQN8uuwI/836yxlZ2fGsi2Z5jRp7ABFt9es0ojaIL9xBO
            qZB0Wle7F0LyfVxLF9TlGGFqZW1/JREoRGfSG1TWRsaFd2YG/y5oaKzweh6cVpff
            aYOORdeDjKgOPTAXbVoLvTOPxRkEWe08p+RHwlvS18ctMKRoG6gEHKPUMTBL3/QG
            GgJhce5MxzXQVTrWB14K/HbZeiudlm7+kO7+5nTHtVARYyAqTcezGeKturKDni6S
            vPJEO2ihtX3Z4tn+dwn4iiFAS4hFBXfwGTTCL0Bb1bV5HbwBouoOJOAe+68DTlAv
            x64NxVuY5GN8tPpeB+tVucyIexYuiiGVtpEXFTJj09TNn84m2QKqNs2fAuWjuRQP
            D6RtBe6zTmRdPzaMiVBcx0KxYjITd4nBvafBSqdOUM3pYCIu3vVyswfbRKm/2I0G
            t7m80tUXCZm8tnD4iMeVodQXq8T7SFg+ZHv45qGqByMR+QORxkS74byye+o0LkPS
            UQEp7oQ2aWspwgEuvFa2LGFl/rLF+jpYkKIum4zDBsIutNuY+qGttVq9+bZbMq+7
            jYoA+9lsvkcp2J7vYgJZfLfeOKIHr8KyPcxqjBtmGOb2zQ==
            =I8eg
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
