# Von scripts/secret.sh erzeugt. Anwenden mit:
#   sops -d secrets/arcane-secrets.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: arcane-secrets
    namespace: arcane
type: Opaque
stringData:
    admin-static-api-key: ENC[AES256_GCM,data:YnL/aIndxu5ADL+x+V0BT3Tce4tZNY6UCY3gqLESiaHt/w2kIGLrD0IpHBnY8jK63OCdTm9ZKRE=,iv:9tdxdptny4O/D67Zw9jWATSf6Xhqg9j40tHPLWHDjII=,tag:ivTY2EzzCzTk+Xq76yVTOg==,type:str]
    jwt-secret: ENC[AES256_GCM,data:bhSrHRyLir7EYfYFB3RMYmrqnY19Y/A1xuhc2OXzi5Q=,iv:sg4nzVOC+IKzK0ABv7JYPmiQoAyrAayHmUVm7M0W99A=,tag:z3Mp6Xwb1usF5+6lDV9B+w==,type:str]
    encryption-key: ENC[AES256_GCM,data:6SJpOgsNQZEDDSneit8cYqGhmGlQW/G10g2pCIEonoE=,iv:j27c/afyL7S2L6z5SZmF4RVdj4+XpeazIz5hVM7B8rA=,tag:XUgURzKuxKuPtPcJu6/DzA==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:M+GPC+n1UbA3shXoSlOv+o+sfxIcoBYTbS+PIrpElb0=,iv:xRbVB3rFDDzbYA9F72ldDNJiVTjIp8F5lPIAiPAN5zY=,tag:vmAlmMxNbGBJ731oqQJvqA==,type:str]
sops:
    lastmodified: "2026-10-01T23:32:24Z"
    mac: ENC[AES256_GCM,data:2alJLpIooe7NbXzX0rKl5Xz+M23y7p3xGvmHt4prlQeos+QN1Oll95ShWzdQIW64i2OFHETxxLhi7dJZffHYMGz6Yo/vWymbFshgZ0LDo3RD5zPH4xhqige3KFl3+aQ2n8AUyFISkYMe92hh7ZnW3CNk0SeP6zOuciocR4mNCOk=,iv:IMBV5jY4bG+I9mxC4JwMZdGOmP9EFffV6uJTMGDJ7SY=,tag:s9u4nqnWr2PlNGA49maT1A==,type:str]
    pgp:
        - created_at: "2026-10-01T23:32:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPAQ/9HCsqXN+8K1f08dYcuMXRpeHr+RDXbhyjevti6umLlchn
            FmzHnreMYXatUX/rbTPvpd/AuV/SzSEhDUnGASk8RyFjKU2GWO/MhfD7XKZkIiJD
            ywwjg9hoJViRIGAIvyPMSOzuZj1mSh46HrxO98oVgpF9Un9svGB87IxPxFZawbEP
            vDRrtSQxOlX9ZvHJ3tD9exviBVo+3h/cNSOxjRoyFBrQryNtk8Xua+N6J+yT4MS3
            A043i2B5nWagjuojsaB2i5ks1gmbSR1K3hwOEz+5Zeslhsi7Roz5zf9s2jilU0nC
            OuIILyeW8y5AU3QgJCw/x+YEbamlkK2746+m7lYdp0g59zk1LQngHr9LVNSpyjHh
            aTQtVpzYBm2wBTm6PSFiNzQZIRwLDhQIZkZKmJ/8Jm1QlfmaJSTr4ic58spSDDmq
            ZDBIFcg/K81vumDaaCGMDiI1yfeKFfrm8SFZ2JQn1nj49WrjGEC6Jckdb67wGGeH
            tMkwFtW+7T5Wsa7cuf/OEC/cNiy829pxRy/M1L8nOGrWkKcPBPmWRkjPzC3vl/Qa
            V2kYd2NYZHiHzFPD23Ka1Z1sJlipW7rddigqqvy/ndf6KpffrRvDh+SwgSjqZWUN
            0BiWUhkkc8BLvyqWZGzu5Dw8Y2du7N2VMJxRU6qtjhBfVLY0LIpSZcGG99Oo/ubS
            XgEIkOAWfE4vpfBQGDNLYjNzSqmZWilUioQ5K5UGfBH3NRqTtmMLUaFxOnOaOAJR
            +89CjwE7RIx5SgF5YRivtKTd9wMVJUV4VZMYrbEgEbiF0gqg24oR0bJBJQ5tbIg=
            =Eebl
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
