# Von scripts/secret.sh erzeugt. Anwenden mit:
#   sops -d secrets/argocd-oidc-secret.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: argocd-oidc-secret
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    oidc.clientSecret: ENC[AES256_GCM,data:Wg/ZM6X4fce+6XTx9s3Y3XXhx+H3kRyuxAUSTYC5YbU=,iv:26IwtuhCmo1kt3he0q9Vtm/4UjdkBQRxiuICAwiM8Ts=,tag:3gQuCcczz+yuIX3GA8qcRQ==,type:str]
sops:
    lastmodified: "2026-10-01T23:12:19Z"
    mac: ENC[AES256_GCM,data:LLKv0/6iYZdtLP78TDT7OP1srkpCPKPLCtsqWVNpnunMCkv046xLY3P9k0TeD2I4XV6G81h5YP4eka/XrwWHkP+puOJIaRy+ebHHCj58McSFr/sDx8tfrnh8Q20oekB93tOTNgWtjd25DSbBCZdAIYYAZEaV9neFx+BaxJlY1rA=,iv:QtctLEmiD67WKxqTpLB3oRroCs3xl8ERUuLu2UWjiCc=,tag:cki0oKzMGMeZxbpGkspSgA==,type:str]
    pgp:
        - created_at: "2026-10-01T23:12:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPAQ/+IDndkqQeOuvtuK2GnHArChvxNbyEfHrkAijwblhgUfAD
            HLIbjlbmDd81J5QU1sHOtD3uPlZgrkkyHQjndjbxjvTz1SIz4z3A3GIzSAekKRht
            0pypjbHEEK0jK9i0R5pMmccN2XIGEJLIcEjxnReY7Hip19OGYqyMVyJ7/wtGImWb
            Xikv3zZAa/03oIQ3Kgd4+4ZBlpVklAPgx2uwaPW5bIdYzSwzcXzIM0UqtwkhxKwH
            z7qAy5X1Ro42oJEAkwnpjR5hvxfRT8DD1rCc9Zdj1cTSwdmBIjZLankzWscSMKYi
            bjRMrCWj0zEb2jSEkc5vDmvZ1MnxbcdfhucbKTXfIuinyVvSOLQcihFAwpGoMunN
            d45T4AOApgoZIAj987viY9ufa6uZsyqKFW7rzN22ZKQKtqCb+fEs7dN2j1gU0JwX
            j90vFy8t1DRjeZADhJ2ouYenfdMbm5ayeis0L1+K3KdfjBPaku9XoqUHSoDfcapr
            syOFWMtLvTmVaOJzVMNZlyRW/RbKfNzEkF3uBvdPXwZcTyS8YL+vCSU1iqBtN1Xk
            HVyZrniC15l9LehOIjyigZfkisACb8rliAQQnQIyo2fQ1PMEiNilV9UOMUie5jqF
            uRk7CWy+DjyTTF/g0RYmm8C5GjPzv0BgeMJ8T2r8VvjzJmGYVLUPE4XIPFwolw7S
            XgEz7KzRxZ+5iJBrLDP7Lq3oaZhqnvbA/RJzyKrTW2xeqJaHRse8J9FzoJi6wfhg
            YxbRq3glAG7DZiaCUWfEBo3kLzcpMuUn6E3kUBmCFZoQghr7JNofKBdkAcWcv+E=
            =xdJa
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
