# Von scripts/registry-credentials.sh erzeugt. Anwenden mit:
#   sops -d secrets/ghcr-charts.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-charts
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:kYWprKe5gG4EIbM=,iv:tiLVCyICiztAx3nNA8sml7iotj1YF9rVw4/ym6NrJRY=,tag:GINJAbMVj4u72YjFRXRoqA==,type:str]
    url: ENC[AES256_GCM,data:ozKtU2uMJgYXYreEDVqJ1ZN8BQ==,iv:AT2j/j51UA13lAjcw9sUrwkHiEwZn7twrOc8xSC4m/s=,tag:/uiSd/QmHZfBqBRh30rHwg==,type:str]
    type: ENC[AES256_GCM,data:rqypzw==,iv:EVnOluotlYFDHQHqPqOM2m0qRNWN4D3fi40H+AN7Ta8=,tag:b0ijo8oSX+nYZLgQ0M+9Aw==,type:str]
    enableOCI: ENC[AES256_GCM,data:dcQQRQ==,iv:ax10aDHshJlnogNYuvi7O8mrdPNTUSZR5hWVvi2a6dA=,tag:ljfoEUxnOJpcgd4hmj5Fyw==,type:str]
    username: ENC[AES256_GCM,data:FEQXPA==,iv:0pz8jVAR9Yo8p6V+NOKU+LQflGx2jp6zci2trqE2gH8=,tag:W419UdhrPC5l3rsDt3jV6Q==,type:str]
    password: ENC[AES256_GCM,data:f7LPPwLkej+j8IXQGpOl6hDqq19p9gVhWb0XuTiodwsvlhJ4MS+hOg==,iv:cWg89KoqJmmP4ZEeauJ8HdrLqxLT5QWc47KynrhUxZ0=,tag:56WcEpS2WDgJUrSeohQHlQ==,type:str]
sops:
    lastmodified: "2026-09-20T00:07:35Z"
    mac: ENC[AES256_GCM,data:QbfHqBAdsExM+gGj5iel4VP2PQUixBSSB/E5SMEq7LgenM8PIuu61y/28ortCKTYkllTXUIFRrOoa8jj/VyoEsC4vWHUZ75oNq38CScLBMO1RMuC0Sgdbgp00orvaQRAaro/ukKuQxnD4DnwsGjbW0R0sov0EENBwMIkxBz8L5o=,iv:ZxZq2mEvi9id74FFR6pfqssUnPBgQ1xC558qxJ+R0sE=,tag:Fpg44S8AJ1wCNd7A7/b6XQ==,type:str]
    pgp:
        - created_at: "2026-09-20T00:07:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPARAAr62EeBE1cCZiCcX3Oo2SQ3r7o1S4yKs5C33UbMfUcT3J
            vYCROuOGIRMfviRAEU3rYD5mP3KkP9sE90dxpqeMKnqV0YubkEhBIwSQwrdMBNAw
            Nno278VRnoBumCp6nz29XZLn0lnwDub8j9RNt97kt1+2wv0VdQ8rQmD27WIWAShA
            K39wUB3Z1m+F2vRq5NjTTt4AQ57C+4ecfXfa3x7X30+zOG/jidT/MtAghjnQ+aiu
            n07ht9pWGlMrAlxcwGMSqzGJt2wsJ16XWDn+xuKQPmfnKyHXlVeg5aEnVZ0Ologa
            p7GZE6xxP3Bx5Zs9DaCPXwWD8xOmpFOHVDTXLEoEpjMPRlRu0+q5T7Acl+MuWF8s
            ZbDuxrm+0v9i2j+D1YEL5E7zLbQidZr1rKLANxQqfNlAl/iHQX5QPFQJZlNFhL5V
            V0UBTZ9e6wgmfhDqhNB7PERIUsuEfrxmlyN8+aiJbJ3FK729X7r7eO8fcHc/aiep
            mNUIEa1+cmekUPfmdvPlCFILinfvJPs0ec2Zgz5fcpC4ZHdDOO6jIU0rym9vH1rL
            OkXyqXb9zF6e5e50yiJD9Q38jRPIZRr+WO2bCkqw1JeR+YUjDp1NlKaAHTMR/nmg
            XrH1xxdq61R9dG84O9pQlrkTsHE/qyxClmlIOolZ9sYwFNpmXzWKn7eUyUhmj/3S
            XgHfPKfxN0pisavqIUcNsm3xcneknTosrYnkwoHbFFVaJQzStFe7JkwMARoexNqL
            AcMkhB0rmqjc/9pulFMBmkuEBkeQGqhriw6PcznXX0nPPVeBU/VsbopOkGaXcDc=
            =I8X0
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
