# Von scripts/secret.sh erzeugt. Anwenden mit:
#   sops -d secrets/hermes-secrets.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: hermes
type: Opaque
stringData:
    SIGNAL_ALLOWED_USERS: ENC[AES256_GCM,data:Q7QN7OhG2E6oDZyFxc3zyMrma5lTosgAX09akcQ4zYqEIfq2mAkd9mu/BledlCtziYM=,iv:knadPMGroUTnAbmPy9uGIVHdVawImr1nIwmUpyH/tAw=,tag:Cw/o9SCQIB1Ibge/+zt8hA==,type:str]
    SIGNAL_HOME_CHANNEL: ENC[AES256_GCM,data:5IvT2HAMWWBSHdoszQ==,iv:8F2V1Z7DayPoXexIGQyBkqjScJKAj6Jnf+b5EVloL/g=,tag:Zuf2QbUDn7Kx/hTF/Nc9ng==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:S7dKZx4=,iv:gVe4qR2HnCnfd0ebzYxheS5V0f243vrOOS9WPkQ92KQ=,tag:eI20FKG8TiIcF+UwUY1Pkg==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:jvwszzv1L1DIRVstnHbKOYVuVEI5St4QotC8kfAPb1EpDPKje98XeGscZnMVIqd/mpgyyaCzUNbEQQk0/tGh7Q==,iv:EyVhb/KIyTvq1auEbkiddAdX4tVMptxlBiyQRV9etRc=,tag:CFWlQB9Hd/4LzZqu5zen1w==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:WbRz2LPoFhbbZM0ksqOERJ50cnykg/uWrN12l2zhmlYyOdsw,iv:1dpceHF3jDqNr4HItgpsaRE0mgY8DL3c3oseNGZXhuM=,tag:CQwEJJ3puwdM/OI5cJOfwg==,type:str]
    SIGNAL_ACCOUNT: ENC[AES256_GCM,data:wzt90KfPbTkhSnnmcGA=,iv:YX6QU4dLIUFPkr6E31pVHTIqOJJMFwPT+jAhH4Pef5E=,tag:pen8LwhY+RUbt6ZS09Sojw==,type:str]
sops:
    lastmodified: "2026-10-05T22:42:25Z"
    mac: ENC[AES256_GCM,data:1Hwg7NK6uXglJY9BRkk+OrEr/EzWx9U9oOryzOQLYcBZY5ZyNI5DORIltmG62i2DodFqlluUHRMNB0B51XnOCOjztL4qGb9kJw3YP2L60T3ZUfZjEdNFB99mSo/iYC6yexPQdI4MgCSAvrjpPhGtxKtxj45k7JMzFErUzTfQjrI=,iv:ZsMeahDhDVOCPHbsrhrsqBdCqm+VpGSodS6KuDuhSCI=,tag:hD4uQldzk033d4ZF9vEOAQ==,type:str]
    pgp:
        - created_at: "2026-10-05T22:42:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPARAAooYdnSmVKce5yRawrMDU1HWRkqOelBdbrL2SpbmoCkpH
            jLahocdymUozdjHRFZKHVs24GLkHzb1H+fUsTsi51QC1FYNdCBHeTU/1BS3fMvoT
            F+OCkA5oMzAMbFxOEExSf5NEA1OztZfpmIzsWGQt7itE8dFvuCxTRxXlTrXJjqtN
            k10lyuoqq25xUi9aonLXr1/mqF6iUqyqh9itx1qb36s+4WMxU6GYS+SBCsK0ZXMo
            bNEGTAWYZcoLjHuhHWb9UhRKT7ezqsVx65puuXoPi8aPBQJ43KUMinmQQPti+ypo
            vU+z7Y8oUiTPijQRSYpz8dGaxv8S8GmjznsOg1aUVTjNKUG9OmSQ95NQ6f3Endh0
            bWNCAL3yESLHPWKVZYAC2A7BDvVBUo2yQDIcZO5ovMi/h2BxUPx8VIFfl7rz0VAW
            w2fF7XpRpExVgWC6i1y0FHjjrTSj4xXYZGCBELednUP/ZHHjs4H4NTk8G59M9FAo
            Mql8eGqjpKXCU8bq1UrgEo4VLe01auQRmVSSzna0oyX/3gWWcdV4e29xuYsirARJ
            KVsWAJrdh9KE41UoHclcV7fyu52i3Xg02b5k23T4KcVIAHnRsiQOsB5LLOoMfS9i
            2nAb4u6grtJy9cmrE0IYw6qOhzQ5//HXP8712k9AhhhMqUG1xvu5YOZZsLsSYrTS
            XgF2HPXRvT9VOIEiXEgMNpecicHFg/UQnByaIhcuARsLTS7IcW+2fp/yn/hdrCDO
            70fiyNpeoyzlU3uUB2E7Izo7bCdTrswob0x/8FhOsOPzNLxAypPS0yNB7GRVjPs=
            =z1rH
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
