# Von scripts/secret.sh erzeugt. Anwenden mit:
#   sops -d secrets/hermes-staff-secrets.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: hermes-staff-secrets
    namespace: hermes
type: Opaque
stringData:
    API_KEY_SEKRETARIAT: ENC[AES256_GCM,data:Vpvb3p1EDpgqNxQ1mXjNcns9zUcPocLjThNlqVBCgI8=,iv:pplPZ+FCHdI6WjyULXzS6JWW6wGWbqZw/ZfwVasiA8Q=,tag:yeUgFQ2t2rghuRUB3bJjQA==,type:str]
    API_KEY_VEREINSBUERO: ENC[AES256_GCM,data:2mBd1YlSHBoVkjURTX63Sruz3hytKH7dicgFODDA0zg=,iv:UIx7lc1BT/yzpsslNU/fjzqffM5k2YF+lSfqHm4jUg8=,tag:3HRCHw3egIGnLwCBGX5PHA==,type:str]
    API_KEY_TAKTWERK: ENC[AES256_GCM,data:TL8V/YvduQRYZL84/cTdkJkYgJ0VbM/AnsXjXyWsEzk=,iv:bHaRJ/3fijUlze+7MtDXEIbTXXm/etCwjsSwBA4DIi0=,tag:DbAaw2dkvcbAf18aA5fCfQ==,type:str]
    API_KEY_TECHNIK: ENC[AES256_GCM,data:65oWCCiX8ot0Dk0TfOMwUklXmMlOkQ990Xfj+AxeKs8=,iv:y1e/YkhgHw6cDjWBpGu1HCtmg5XC0mCBcdIzD75WUW0=,tag:N3pHMBzKMNOZWkn+G6PC/A==,type:str]
sops:
    lastmodified: "2026-10-06T23:39:29Z"
    mac: ENC[AES256_GCM,data:FxwLv7C3WUqpLuo+GFhPwJXUgLtefahI3x3gxeXvBdw13GpPPeNyPmzsp0QlXUszw65AhrB+fGvAxF1NSFjvmPMs7LBqgprdcXhrtlvIEpza6S1l4VPz+bYJpkko8ITSfLJ6nTZlQSzmF2kk6YaYX00xajyKKN5Ddke46sNOuqE=,iv:EgjI6SYKgZH4byi6ChtDOgQxpoVFOQrafqFUfOPOdA8=,tag:h8nzPVCGLHxt2JzB+iV6zA==,type:str]
    pgp:
        - created_at: "2026-10-06T23:39:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPAQ//cBw4485PTrcysfMrBKw4BDdiUaCk5KKMFqfoHqvReTo6
            RUE0Trv3532lpbSMrJAwnAvFMo8qsOPbfMwTYCDTyFBxIf5M+bbFKeGZ6OkkOQ7q
            0m/uuR8YLWtybR6wnGwoF/g6WfLNbJK9QXDztUj26zzssPGT3By1jiEDxiYS8Z6C
            1q6zkuwyCrszZUBazdmtLRsZ+Zboakb0tlm3FA8llsCJ6VxoURtcv4w2/61/puQw
            3edUWczL1+GshgtvGxArbAu1c6u8wmI6VyG4wqH1a+qLG6BA64wYBgpDFOUhVLND
            /TzAe2obkkAmIn475lvhw+A82j3NsfgHx0MD1iKzQm1mezMrdFP4r5Gvy7v0XZKG
            N5/l+bIhKvF+myuVZOANXgUE6CS5eqIrIQX0MuOSF4A/6s7cA0kU7FJGHp0ykgUF
            FHj0prbjPwK90GAMbrj5tKy1xqxGteDwuPbOOiy90k5qNstHKbMvdVyHi6x1dKSC
            XRWPhzOc2uKpnv711FLJTLHpzvheMbMSuxHwuo5P4CjS7fbyeY68r+zkJqySzgsO
            JFPx71BL/sTs1nt91dirkGRgcJsfy/Ckf68YZoQ/JJf4/cs1HMi9jXiknDXL9qZ8
            bQOV67ZeO21joWc/a2DSzsYyDFbXBJQxEBRG5ZdLsSDZwSymIR9NogXQZxs4gDPS
            XgHjZPtx8vjCSf4S1lNJhpSQqrCZtxruPskUsJ/i5z5QL/QWP0sf06f/SDSQgWBI
            FG6BPqMw5HOOVCYGUTit7R2vJNlTmr8miTIkY2HcDv9d7CIAJD+rruULEYHoAgc=
            =MX6r
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
