apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-api
    namespace: tekton-pipelines
stringData:
    HA_TOKEN: ENC[AES256_GCM,data:8v9My2H1v90Vpqlop+gSb+BcDzjy8tvQMFXCgbtNc14Q0esVvRk6TTO6oGnvYxwM1zQMoxHSLHnHiqcmFS5dfURrnLU1e8GWN9l93iOJ1YtAp6RUIA1kwjVBjR5f5yfvJLtQEmoD3qV79s4+8ppeVkJZ6cF11L7d/st/Vzt/Gsoro/27V1isKrNBnAGpMsrHlNdWWv2zsPAPZO+J2NOh2GmSK3+05FH9Bx66Zdi7EIpHb6c//w+z,iv:dMO+3yak/H/66er+jQhN1LnqFW34Rm2Qdc7oZemtze4=,tag:VF7AhYvilKTBCa2uh2yPYw==,type:str]
sops:
    lastmodified: "2026-09-15T23:01:55Z"
    mac: ENC[AES256_GCM,data:VpgVUxNQosRorK85LYTl2T4LPzYu4GI2le2ZGvM2YVp7O/jDY9CS+AiS1+cxlpwQ//0hPwWFwpDEQuYAVqzckKWTLIXDWGOSijZJ9YkfVIPN+40RpFLkWlWXOU/JzNhBAFfVp8W1pvhQUvBrDtVJaf2cMtyKo1//huyyjvVJiko=,iv:KfN7vUU5vQF1YirtxuOait7/VB8TlcsZJsQKjWrXa4Y=,tag:Lou9erOAEyK+DE2zd64yog==,type:str]
    pgp:
        - created_at: "2026-09-15T23:01:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPAQ/+LWWzDUNWu+KXSc3LhJtEUE5OTYR5tM26cRbtZ/HqIl5g
            Ht2GnqhESCqBqOzkM5pRuUpYlz81f3hfRIjVWCIxXx3Lc0s/ezlkiP0LRB5NaO1q
            9u0i84b5YOhmE5VlTUuTJQCxLAHvzI8Fg0MLKt5HSGYsGHGablx63WG4AS8j/f9y
            hbc6qIf+DiSVdLcpD/UAEypRH8MXAJEvXkY6bHWLwXT88Uh1VEZKNAPOzG91eE9V
            f/QWpfZ4VAcTIyvzh4vItf0ao4GViGVzINjQfkp9vbszrqsC+TADyyP/VS7XJKUn
            KBjLnrzl8u/exR4qqLgaHcTRSaTm03RrGa4Sm6MIdBXzwOFtIFVvrqKVg/IFTpFt
            Mu9wALAhquIBSubSgio3jyeVEmhZCpwSK3Q6kh2GPs/A4JdG2aMovIFZt6/leOHk
            bTJzOw6tb/SZ2Z8HZ5mN/tigQ6OGw1hZS9Vk+JUMCY+LjM3XYFSiTbpBjw1vJy40
            2IwTy37ODXrBUIPovG+DS8dJYboDOqaRfIzqg2PG79DRh1XNSg3z5WFnEZuRqpxF
            BSwWAxqo2VjUKMAXxikOg8KxO3Qbm/HNPLLj1kdatv0nZG3pitxuoQvvs21aNdqY
            6CJJNYuK5Kn2tItSr8643md5S0Puq6YDGDx2g7yX0zMolbeRvB+i8A+sl+fL35DS
            XgFbCMaUtZWFZ9Xu/dim3Caoozcn6o5RM4UJFYbpTdshVAkHDyKh0uGa1UPIGZtJ
            N6zVSux3y9pMrk5YKKV8W3CU89ecD2c/SRYnKECXXsmSQBnifYr5LDXfg+owVfk=
            =5RbA
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
