apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-assistant
stringData:
    secrets.yaml: ENC[AES256_GCM,data:vHVUt5O9Ou9XOMkf2jAo3sBFGY8VDXBS9zpNbp8Xv2v+XQjtnGiPj/0fGdf2XhnhV+1T/JGUqPSIK2SMDvP5lsK3JKqLefJGQQ1JbyzVvInR3BTQL0IoIC4s9Mm63f+RAH6ptEyRjW3uuja1neFJNrkFiBgYM/bA/0WHUnDL4p6Qp3wp81A2RtnbXplTDmJmwe71gcVRKiRXe7b/PhyDgJ07PrkowCcMd+epRiU+hAq0v5z4C1Yd3JO3nDHnBOqyI+IPRvhHyS/rVsDNkIuKLvZIvljVC7jIcvYBK5/rZYw1ibOZ4qGAV+hbB/Bmf1vhaBdJl/3yKLq9YYYITOIquKkZWAm/gAdbspfvVH9LVErbodmzj6Gl4K4bibhejfA5DhISBDeWL9D1syyEV/gmibdKlx+5cib1wdSlqAAQBDPLaaTLS3thPgWuyOGK/HV7XCXqdq6LWr1D+oVMH4OsxL+w1G2W9xUQUMk7qC9gUwJoNgT03YUPERhGBm5iGBT/SQ0h5KEvZStIttmKOcJVQGU=,iv:pocsAFw+SVxlgAzbGBqTQJc46DgvmW9YQMYM/kTdQWU=,tag:mc61vvO735nCWRd6vox1bg==,type:str]
sops:
    lastmodified: "2026-09-15T22:33:51Z"
    mac: ENC[AES256_GCM,data:yu0Pfwqy6AfC83xpiY8TLmPK8qvJgwvtmpCKuia3BfQnyj5dEeflg9YN8rAe17yznDedrjRRuSHjGvZHxrwAP2pwad6G6l/JxOQA+V7RV0gQwAGSGT6hRT0ufSQeBOWluejHXcWHP67gE53KYdvRHvuNLBQmUNXSLsD+xVWfhAY=,iv:JLLwg1u6hKeLMiEx5fCOY32+8IBeGVlPSKIX48vxjGk=,tag:EnZFi1yBnYUul1GGf5RO9Q==,type:str]
    pgp:
        - created_at: "2026-09-15T22:33:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPARAAkg7foJr63b/9eBgbrt6f0lJphfvKtce/jlvCSrTgBsnG
            j1ks3O3Eq3UbFP59C7XaORb3TjIrqIDWc33FtTlor/778QjBzl2lUDC8HnrKxjBP
            VGZWy4YeALBbC3k/brPYnCNHmvmOHspd8C5vBA3ueBa1D0BtmKWUCviPTdemNNx0
            /0CKCME0TdoAs2wkF4vpRQrbjYUK3Q8UJqX/83JJqaXrgKKrJ+UnADdy6RSycFaW
            6fBIwv0i7+wtJtZ6t7I/wdAe98FLPl/j8Fg9TWQv2zLahmYVlLZqdvTPrqk6L1E/
            h0s85Be7eXthru8Wchh7c2V4TWutSGYKT6AWdA3AG91tLi40JCcI46wm+bJBA3MH
            gaBLxZPJhv3d4j/qkSEUCElq4vPTpAegz/N1ikfrpxs2r/vwWcMSnjrLdIe58Mvm
            krpxs5n8d27kL7Sj/Tfv89CsWrMMtjPic7WljA/kYBL4e49po9j8J2weHtKijcKY
            AFv5J7pJqtj2Bq94vaO1r41aUcWlekHZqF0DYTbkrOLHlYe+9aaFKZ4KCsI1zz6g
            R+Hr117ckiMbf1rKvauwOW9HfY2DxzUkn3Ejg0gmyyv8Fev6hmzodlcaqex51ERL
            kxQmfjzmKB4Mwar0wFdwhUFP2wPg4AZKVtGA0eCFh0qtSbyoAkQ+d+A+skCakDPS
            XgFIn0BHXISokjZxlHKHzwevuK78AEUB9OMgk87iJ06FU80yiIlw0l4L+MeJwU9J
            9qS7tnTMxtDvZp5fkrcDrfvRrtGcSNHCBYO5g9HNFmnWDGv/+//otiBhW4j50JM=
            =P0TD
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
