# Von scripts/secret.sh erzeugt. Anwenden mit:
#   sops -d secrets/newt-credentials.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: newt-credentials
    namespace: newt
type: Opaque
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:2H+ZF1Ahhbj3C3BokocggomIU2MB,iv:8mxJRK9zGweHSpxnWFogiZ2i+D3NqOkOq7g2ubk3ljM=,tag:SMwDk3Nmq+gKegUuge4d6g==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:3H3ANQcjiWXqLVRhBidR,iv:jw0+RH4Tbo3uvRaqqwUmXOxpL1je2+cgFrbXP41z+G4=,tag:gay/iIDRFXSi7/1KZPSNGg==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:WUftXvM9Ndj1rzSy9GVkyMmzP1RF45teiGmd8fr2X8Li2ILxtakZGDS8iNWMkKOh,iv:YdOVJ0mnGRwmbfCN5UbXjw6XDDKMuQYxRJzXnf90cbc=,tag:ELrSW2/a4BGFD3xKK/soJw==,type:str]
sops:
    lastmodified: "2026-09-06T00:49:31Z"
    mac: ENC[AES256_GCM,data:QdlkW9TQQgV+Q2y6AYgx0dkAdJ5ZwP/NLQ/rzitcXtTYJO8E+BAULC/awdApl1LXe82Ji+a89qL74JovbKInK9S+0PI6Qvo3ku9v7ihezlDlAyuR1XKL3IKJCL+LyBe9Fi5ozK0av1W42DheLZWOcVhsd+caEZcq0r2xW3sZdwQ=,iv:eL25C/Lm/M4qjLR6+jrnn39jVOHFe+ZORbocH6R06bQ=,tag:uaTdl/OQQHrehmQChzhoQw==,type:str]
    pgp:
        - created_at: "2026-09-06T00:49:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPARAAq5sIR+gzW9JWoVPte1WR11xmeJQN3hQUZzFveIa7jUtA
            OAnp5l6D9egemK1g8YlIKXi2TXDs5aOeebCFEG19C74B7Rhw/CytluVdEiNVT6Yr
            7agZXyYC/DVZgYRvRFYbqheITLxlx995MyM0CxGNXaFJs1BX41HHaYw8aJzDL8W5
            b44P/2ejYD+Gypu19l1eBJLyKAIildhkWSNfN4/zwA2YfofNWmQcQtOJCKQJ6pAz
            iBmnN4M0SBzXHjNofwyELS9ntwAirNNt/1lyhJxU6zNJqVIS88WxuqfmUwV+ZjYm
            7CKC6gwb9bJGqNzIaTaAyFAozODMWl5FVX6G8GQZq7D6knWrWSrvSFtxHP5svGRZ
            P0GDcZRF9f0q31adndh02hAMwi4OIlh1DRcadm7easX+kTBowUebMRsEqsWyy3a6
            9KfoYhorSXOxoGM2xAabTgOygKeWU1D/IWOqXfcbCKRh8NRswWh3lHu5tY6sWd0D
            ukTQdod8Fwy+9qPfxFD2SP84uU4w/8NvHAHDZx7Y9UAgS4T0pGNe3Aa6FcVs0FVf
            Q+tepux+iOl46o01AZgIlZmwej0+DYAfzrKh3wTcV5bK7x9FXT/EW7NE4/fCYSke
            nzgXURxrCIa4VmKHL5B7uEHgi7TrQ5Ql/TOcwtpb0Z1iCo9na+MgoqVtGCxvZ5/S
            XgEazB3UYaOTJC0g8haUjNuURB/VDWiUxSlTQPRaovI6TAL1qNGeRtrj+KXT2JbR
            4o5CzRkeLxudp7+E19M9M+XCxR47H3zVJvfkqF/ELN4rqwAU4NCkpM6byCK558g=
            =qiSd
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
