# Von scripts/secret.sh erzeugt. Anwenden mit:
#   sops -d secrets/pangolin-gateway-credentials.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: pangolin-gateway-credentials
    namespace: pangolin-gateway
type: Opaque
stringData:
    PANGOLIN_API_KEY: ENC[AES256_GCM,data:iqWQMqjUqg/RMry9pSpIM2SRF8Vum100kZpwATK++UeR1svux9hb5EidGJc+9ZRWjn2XVfm2omU=,iv:RZxjI78wE/D8+LrBphXDSTW0knijRt0oKc+4fZB1Z4I=,tag:i/Tdz4UPFt7YuWc19SmpqA==,type:str]
sops:
    lastmodified: "2026-09-19T21:35:06Z"
    mac: ENC[AES256_GCM,data:KWCYpJrLnK242v838NzyCEVpf5yNMAwI2C7/qcVFnOprAbOEmjqK0R/UrfTp9yjskWKtrirS6AOfkpHJBExg1detZZS2s1iUsCLCnno+RjvmvuCTkcTCgbAo6nPzrw+aAJs8gksWBt3BWw8nkxylwbb+P/HGmfrp1HgwHga/XmU=,iv:m872KrYsbxQQPLazmFfr1PO3ScmYj8h0T7vD3296blI=,tag:9eHaaTOJuwXZRyzoBIe0mg==,type:str]
    pgp:
        - created_at: "2026-09-19T21:35:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPAQ/+K5996zX/gvYctp8rBiXtBNIKGqqVxtrIF6CWL6jL5HGf
            NwCbtzz+yvSBlGzmSvR0E3XE7p7bg2NT82peJgBeHolM8kilRiV5JNVH0u2jf17O
            8Cy/kYpsbl4HILoEVgGAf9PMWDi92lUvgVwLp8x3UtN42ywnHv4tc3b8sr3C4ylz
            eVHcj+0jyJXuD3a43EtoBhi3vgkBtEfVHpwNQuvpR0EhglgAsdVb24HgrXETJ/d6
            IDTeBbbpBCYZljG137zYOTLyTOqBisIkrSLVt30i2MwzpvBy/kuQj97RrmC/UF3l
            CcxVoZUttTJ4M77BK25HMkb+/aWGimQv0lNNRExfKC7JxhYpi454t3MRqAAmSbSV
            vBNaLFBNvUxgkrb89m3S5yNxXDQ2ndkpdugSl6YObW07Vcg0ByqbaYs93XRqDMnN
            msRrDx/IGpplJBnhYavPTNxqoiZamVCvvBUMtK47nFtiTICb7lXzb9cWQ9j4gPvh
            bAKMj4VACLn+BlD2KEiAJgB2Fouoz0CntJNyHCubnk4TgPgOqoSlErygKzmRvnSe
            WX6qJgcTfTVjwfadnoZyhfRU57qO95URaiLW2U6WCr6D4Y7HdO0MqUazuNuD8oP1
            /8RgT4YQAiJHaFOWNymFiySrH4qorrDl8QG49kQfYJ6REDsyk33MFLqQzkB5yKHS
            XgG9XPFEJBwYELOg2IfXrIX31K37xrFnTDE0g7DREGcnkzPy1eQv/K2//vVw9EJw
            YaEtSBgheXop6WWdUFmb3XMpdJJfcopnlKDntutZolmaBjUL1kBBylok5mGJoN4=
            =baOH
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
