# Von Hand anwenden, nicht von ArgoCD verwaltet:
#   sops -d secrets/pangolin-credentials.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: pangolin-credentials
    namespace: tekton-pipelines
type: Opaque
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:MqY0i18NgMs/DZYpu7saQzm2z79Ja4at,iv:7UND/Vc1VSee9KXOCQjPG864Ax86XzQgo3dpn6NKuWU=,tag:IbwSGs61uP5BJp6XfiG23Q==,type:str]
    PANGOLIN_INTEGRATION_API_KEY: ENC[AES256_GCM,data:TEE1STTnZFDAYQ0B4eKsOuXjnqUr1LSdDQNW0cJtGiidmut8Y/1yEzJNv6oMeOSE4c7hpzxGsg4=,iv:IXGkQvIAyZ4QDyFHqvuXy4C6oFTeF9h2HvofEXRIxIE=,tag:K4AtNU+CnHJCqQA8OP2Fkw==,type:str]
    PANGOLIN_ORG_ID: ENC[AES256_GCM,data:tOo2VHuYquqnM2cELg==,iv:XhhPjAY53e9+M0Y/jCBScWYlJpvjHee/cOdI2v1qPEQ=,tag:BUfuFxWA7JyZsBIC8BNXtQ==,type:str]
sops:
    lastmodified: "2026-09-06T02:17:35Z"
    mac: ENC[AES256_GCM,data:vWRKJo/ZcPD1MYC+pM/2FsAeVkfQAmp/GBeVP40K++E5M9rNfEnvM1b9l02yvIz2w3efM3Z6xURHM0Hx6z0p2u1yRjPrLv2QmJh0faTYc+fvnISkV4MFNQshnxp7lNOqiUuzr8NvD7/xGvr1vRYqjrxgjS13ziM66ZcSsreeR18=,iv:a3s/RFCeyIKy6L3rEjN93UqhWOYtrme/+h9nFQcMpag=,tag:AF8fKVKoyYyZAB/O+cUveA==,type:str]
    pgp:
        - created_at: "2026-09-06T02:17:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPAQ/5AXVOXjqkf6+qrMiQSkNZA3CE8pZ0gXbsMxsOc2T8lLSy
            9jdeBX8/bdrUAffYsq2i1rMUGdvT1hjDYqiidHdx/1QhBSoqpGlLpUpGrvuFUWd8
            9ej0TFfIqcnp1+ICCTfaWyBdV3L4KkpIvrh9Gb9FtXlA+Y11n+5fz9IRJ2KCURtg
            IUstXU0oxAnrx9v6LGuHDJxuk9yPn/WKFCCW+YxnC3gsxQzT7aFf/nA8V99YoD/V
            g7S9EDYqGAcuHgkN9go1Y8bUo34SF3f/dkpFT68lwjnpDdls2qaSOTFf9KlOEaB0
            Z8qIn+D+Awlb+e+p6saRXlSYBYStAOOYwndSFkTERJykmkotJw+zzeQ0C8EPjPfd
            munaod5Qna8/y+GFZDN0+gf91NHUNcMAisPnqCJHyEZfjz5mCW4WkJ/9KrGDV5EI
            VqENAxtR8TRJxsKAb35mMTKs2SxUYfQvcHPg35DpN8Qg/2hKL7ANLPAs1GaZGeZv
            L2uFz3p5L2JiGejF7ZOvHvV1ZcM7fFR430le1/qk2VHl9gPKmKLvfISEj9L40nbZ
            7NNSgCD9CPt0OWftoblH337BjjRmQWUa7PvXnrOgxxSiYHiCToJ17hhvPOlpuX79
            2535BOI9HE4NpqaQCyc9aTL2AGanCK+gzGnz8iXisKeZNDfp5RRpBFtU/5Duw/vS
            XgHsw/U4VInv12nvEZGC3ZuMZtVek18tn3UIXEawz1VB1Vj2Pd/LW3v/GrvtD8Si
            YUM7kNuytkdVqYjSbsrtcjmtsBG3ZnIHmY/MmKHP3F2Nw4fNWKnyasgraS6YtRI=
            =5zQ8
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
