# Von scripts/secret.sh erzeugt. Anwenden mit:
#   sops -d secrets/paperless-restore-secrets.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: paperless-restore-secrets
    namespace: paperless-restore
type: Opaque
stringData:
    RCLONE_CONFIG_SCW_ACCESS_KEY_ID: ENC[AES256_GCM,data:8rnAu50QvCeO2Wmok2ekw+IBnzU=,iv:Fndo777173ob02NMLW33iI56M6AdozJkinLva0eaBxg=,tag:jAh08o0v3eGDoGhotbl4jQ==,type:str]
    RCLONE_CONFIG_SCW_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9Z0R563WUFOZ9tA4ln7lOm/kmdk5zC9X3cN9eaFbXkQshPjP,iv:oCrb5G1VreDqebsoNN1/KNBwEpD/rMuW9TXq1+YWVYE=,tag:AN8IvsfG6g9xu+XwuCG66g==,type:str]
    SCW_BUCKET: ENC[AES256_GCM,data:UZh8a1NgU5BV0o8=,iv:UoZeG+d9o3oUXepeX22CGFrm7nkWecDTbNdTo0pXA6I=,tag:hFljfQXd9wDeW7h1lal5HQ==,type:str]
sops:
    lastmodified: "2026-09-06T16:13:44Z"
    mac: ENC[AES256_GCM,data:gctlX/ZKdeEYuN6VmGIi2l4tk/wrgJbzTNINE0lxcP28ZOAah/5AqJrHoGPywD4COX44URLoPC4i9XXwLA1RJMOYQsG00TTJLftAtEjVeVKKFKWn6W93oaY2k64L1Q2gPDcJ/NzHBxxdUklrNLE+zz3Yd7dHvKKuJr7lxmaKyJQ=,iv:ICvzLnYYT4p+j3oXzlHbzVe8lrtU+KBG92YKKgob0S8=,tag:ivhdjcc9Fl3xB4KsVWEuSA==,type:str]
    pgp:
        - created_at: "2026-09-06T16:13:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPAQ/9G2BqiZmFEGVF3G5IMAQ1xuTivfOlT59JWtYEOoo9gwp5
            2vSeq8Mu40NzzykFIPcgZNf8SO34TU3ynH9Bx0eRCLu6YInKZiibrZCyQ9znh3UA
            aQDnYI4DweUrJkk96ZzM/S/VLNbNBM0sB8WT1yuubwcr2OVH+LX+VTDFbEbid0lx
            ZX6NTPIFHAti9iM05XxJEn8HSIx8vd63krlXGehBAjhY/95aiI1loWNIaEGndMyH
            T1ZILPXTh9mspnNMOpAMDkCLC4onexTesRlUI3l7fZw7OfjEw6d67ptz6NAg1Fkd
            YVayLPofGot05VMZVMfCjOgy9yrKyzqZSvEqfeNd21GkefTWMAzwd8nCf3uQutLf
            qobB0xcsQ3DImyD2ahmWuDhFB0L9DJZhRUdleqkAzO5jmzn5ClandIF+T7kfjbxa
            8gsBvPa4NSciTRFUJE7mI/Gzz3o4THibL0md1AuaHkwRudKoBQf3p5ZuYaN3Rufy
            U9YBFmiYcFt7KHreNrU/pKdU2li+cEPPP79ZW0v5wpLOND1/QuZjT65/nengKcu5
            LoWHjtiC3OQqVAjT6o4nSx4LzpjDpEUgkKxdz01rtMTQpCMOls2nt+k3RrylB6qc
            ZAavEuYdGFVO32gdkps3bLip1t0+ywt+yj8InaVMMh1+2v/IPLsMLvm89dinONPS
            XgGTxpJXmKAK0thB2MMx8eGRcHbwo+sF62eT5MsO1XCHksdsuAc7bKiToN8YKmBm
            FKM2III+8a7NEsazNVgXdQl8ZTUWMFDaBtUbSxTdviCo8Vk7W4EITOpNoWprHf0=
            =YS1q
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
