# Von scripts/secret.sh erzeugt. Anwenden mit:
#   sops -d secrets/paperless-secrets.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:ZkeobThKaqace9c64K6F747jVTwbTnWJ1hwfB3AjnOaNGGjw1VWfXHD3Am+qDwb8IPhiuMf8S3lLrX1Zi7lX7Y5Y+pJTnxKBC1X6B/oozhHbc8MO4eg=,iv:I7udpp2MVE6ChAqEhOwLMYzHQhY6XHCzx9wgXJGIemk=,tag:boSZyVFYt7WyTUPhL8jsUg==,type:str]
    PAPERLESS_EMAIL_HOST_USER: ENC[AES256_GCM,data:8vmazq06LSdU0adfeENtj9Dm,iv:2P7c4OKsUBaRCZXDf5qhbOZP1jjZcwwZPXT3IZthglw=,tag:l3/pX93nJCJAOokjIfWLQQ==,type:str]
    RCLONE_CONFIG_SCW_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:G3CesfnQLWlWnwceC/oI4m5X4cG56DNzlRJZ0UAk4JFKXkMK,iv:zv9AnUCC4rm3kvT7dl+nR1N4ljWfKZRdWtVWls64MRc=,tag:0KJ+xpyhPiomzLd7CR/d3Q==,type:str]
    RCLONE_CONFIG_SCW_ACCESS_KEY_ID: ENC[AES256_GCM,data:Vw40ZWw5Z7xfdzTzLJr+b4GWcy4=,iv:Y7yygUVNvljZiSq4Aaf7xjluP9+dlbTddtajMhCX4GE=,tag:s6rtNJLwmvnrO/ze0Zk2/g==,type:str]
    PAPERLESS_EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:e6103mFuwiPT1zxwI7D5ZNoMH+pWyhR4q46iuUrdzlU=,iv:GJmWnTFcfEuc4NWp7/kSV9OLWf+YuqzZWdXdsRIUX38=,tag:ulZLAUw6OlU9hIAB3TQrWg==,type:str]
    SCW_BUCKET: ENC[AES256_GCM,data:2mrGx5s4wz4Cquo=,iv:I9c747p+UXOnBr6AYDNweJLAhAqX3Eno3bND7bbetdk=,tag:dYaE7r85NSWndHJbif4BaA==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:+SXxXBgunMsifoW/BCq3AOFkBuhvNy3/m9kixPD5ATyw2+tKE1EW8zPN1sPChORTLtpOGCQ0tJL6KKRY+VoqztyerWEF8giL/RvBjJO+FCPsuFhbccY9zSZy7HsAUDr1A4U1s4KPZtxgTHkcq9EAdqpmagh1E2DPJAmKf9/5vlzt8BhRM9pTCQju1UppoThFeyB+eaKkthkeLCPDbW2vYGxwy3vvFH3nHKg5D7CVySLyVG6mnETEnnemqo7vrl1tDVD39j2N23RDfz0EzG56d17m5w+oD8m/+QiLoLirrSElHwD7/DP/rfmOLpl8UiOtLcEDFwmAD/L3vSj0Rhsq986UCXrjpHBB4IakVP1fkGkH1IyMwvpKq8+ENsSI0G88yGn/7DOKbxDr+fUyFepy3Nj9HYrSk4LT3rFmgRwNIGCz2fsZtCZJdMEv4pszSINoxa0GEZjpG9tHqbzWQRRwSp7je3BLH8VM,iv:/e7Mhpt6ylbuAf+lgOeIz4INl9BZpPB6G6wInj2QB3w=,tag:cTkAKbRMf3wFQKYFm4JrTw==,type:str]
sops:
    lastmodified: "2026-09-06T17:17:47Z"
    mac: ENC[AES256_GCM,data:2tpwGn3XPrBHEAuxjsIb5N1O+ZCgOFYpP2D/FO5z/w3QGEARPu5fMjQis4xp+tOC4k81WvnJ9lp34aZQtmPsXl9u+uPcSKc6g7zo+tgE2Kvdkaez1RUeunp2DdWgkrn5V5DK6aS/P0n1OIZ8pGzBnpMDCJDZIHlmdP3Cr8uLYFQ=,iv:940xA7m34sCYyzxdPtFc8IHpCcaHDFfaLZkF20VdTQ0=,tag:oGxspAF7PchaL1TnjNnpBA==,type:str]
    pgp:
        - created_at: "2026-09-06T17:17:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPAQ//apSxm0tGOPfQXce5UZt2ixBPSkwgMuG5RPA4pHlNzKOZ
            eSUKU/BPbE5ayV7cvM6mSqGUf2QVgcgLqNqfGZlbeqCn8TILfyAXvV1XqfCD0YfS
            q6PR9k0zmIE1wvgKgwGiwWhwBI3biqhtLcKPuF44UslKiVZCoHuey7qWGJ+/qM+m
            E7jaRxqaGbh32P9CYalJtDi+ThudIoBFpGoBi/OwH+spQCNEXhvWur1M6OwQx0EJ
            kdO7u2Y5QUJgXyTquleQZiAKMCxfYdQuznf3MPj1BwwS0jltDbPP4T09KH/R9kyg
            gXs/EkUxbZ6VjDUHphs9OJZitlAXl7umuLSPkIGY2B8amVxemkqtAOHBSG+WHs0G
            bZdAGgu6PguJVqaTq+Dfgl3eFvcwEZnZx0HHpVTtWgHyO7R8qxP41za0QFSqYFsW
            LXEQHVzYwRmYY8tEURNj1p69tEdyM4w6EDBaJp1/0SZ7CC2sjgajwryrnqYibXcn
            Jxxw1MzqZdTku8S7iG2LXqY7xmedijHgdWP3kkQZlb6MwOhaBnSja9xTHJzp6gDC
            t7GkNQu7FLeW8V8bIKWrPkIMbnA8aLMwO5jhoCkoldtqGJBj1A/jnPn4YMOq7ap1
            lPEM3GDxTGtRt43cr2d9eyW5pnsD/hQtqZ7xwYKIAms+HifowprRBfSc3G8cF4DS
            UQF3kcFzLxhXpkhm7LkXBOvDc4pZxO3xWCt02c0F6s0jXvwwI82NllPsBQ10aqRh
            ke0zAQ+tA3NFyZ7DenIuf/Aa/UEKLFrlaf18f4PCN+aQSA==
            =zN3y
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
