# Von scripts/secret.sh erzeugt. Anwenden mit:
#   sops -d secrets/paperless-secrets.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:bhFvE5bIgF9B/RQ7AK2HrhVpXqrR9M1HmDgdtOrGJZKD82CW0urQOluotMCBhns7ycztWQaTd9TdaGery08yFzaKr+h0j/PCQWntH8DfRaIMn/0fLEAOqr8VOTXZDaQfOKllfcO0GV09DOECRC9vfRApZOrBehtoc5iJ88KVqcaMcInTcnN13WAUhhox3kPiUSLJcB6YUu70k4UO/y0dONS8S93tULQTdpSpk1vqkxi7Ycu5oERXnidrhM24f0EoIgbN1Vrghu3/8g8pP8D6cPwy+oNapsq8zaN0NZ6j54x+1aeWFWnPPpoVPZeARQX2Z2vuUspHQTF8Uh8G1ufe5koVqcsFoxxg8nYwyIIR3kmLEPzFJmS8QvRobIlS0xAbcyLEzxzr0yX1e8FA19pxqjoCT+vwGkJpqnILuzmH9555L38kZ7iVx5Wakegw0sv/cSuBtk8oc0zBUb9LTYleDV2Cj8PLT67U,iv:gLC80vJ64VW964TDXYsWw+ZTeFj09UQ33Rl2s1CGJho=,tag:4/EkbammNWxqiH0+W2Zqnw==,type:str]
    PAPERLESS_EMAIL_HOST_USER: ENC[AES256_GCM,data:62kSZ28s/n8CzO6ZFd/GzVGt,iv:I+ChOuN55TpBv1ENenMDvcZMDntEqHQyTewS4PBAmc0=,tag:bXzyhnyOtxBOtv1udCFsTw==,type:str]
    RCLONE_CONFIG_SCW_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3NTw1z32mo/9oGPWo0uXN8jbK+QvL+M0XYpdo6fB4UUTiLhb,iv:y5Esh/RnB/sUtR13eCDgrhv6rSj/dhRqIE4ec5RjwKQ=,tag:wAIEooMaI/aLhcEECDr9Og==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:y9jLVOuOidBYgXBbqQg7ho8O9kNoHCYrCAmZPuz6FEN4SiePtchW2EWI8shLpC1W,iv:pPyKTuYj0X9P4T04EHL1iHzoNvsh6Fk2/xc7MHaAhAA=,tag:Mwu5SCoT5P3N4rKuQhogDQ==,type:str]
    RCLONE_CONFIG_SCW_ACCESS_KEY_ID: ENC[AES256_GCM,data:EWHPj9f8+CHvpTguUleptdykCM4=,iv:4QEPUsE2JClD2iBCQ19yvZ23uabrXdRLJGMHkgCOQj8=,tag:Cort9JvIaYHcsSwvGILZcg==,type:str]
    PAPERLESS_EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:4XloOftwJqBeGQwa4n5Oq/J+u9ZXwk0/Bi5mgWCLCa8=,iv:RvI5/q+LoHNoDvMKNch4RiggSLcmOohuc2UmncRGDQk=,tag:Gl7+flOX4WC4rGprb8cwJg==,type:str]
    SCW_BUCKET: ENC[AES256_GCM,data:vPYReao+6hSvVi4=,iv:V1gD4+js3Vt9QqaBdX88R+TRBjxp0ZadchFBg3mebKU=,tag:nPJF7Kmgf14IfvHfJx26sg==,type:str]
sops:
    lastmodified: "2026-09-06T15:57:29Z"
    mac: ENC[AES256_GCM,data:W+1xrKtEWCyIoZBUuOkK5AbaqEtPiHT9+fH/V49jvuKl1/10rY5qZwB7C+OLUIUTFwzWwxUToimVz2FusPDtGORMsoX/iCUDaALY2SUFFUfAT+QcuWVWWOVrpuZQS5Q9BRvxvePxpHryQwaIvxbcQzBlJRO6GbfghL8mS2+c0KQ=,iv:EWsj59OPk1asg+Bh+vG/DwuEKh++wBwzOANQ9nelzCc=,tag:uuXXlWTLLOQ2h0JZWv8DqA==,type:str]
    pgp:
        - created_at: "2026-09-06T15:57:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPAQ//XXCE+amL/wb9/zkSouyy1k+6T+Ik42J8uZk8sXTmECTC
            TcV7jjxkHZP6IsqNN/ARHhL362GoBnE4n7pea1qczAuDkogdZx4KtLZYwDWVE8Zz
            H+SJOeM4aguOZOhZHY7RzpLBhl46iPUZjIWVaBgXhn1tGFf4aiXXIGrDGQyshbNd
            ZfQQAmt+EzbTNB/1MVMGykCMprAhyphyALaSU49BH1bd6td/w1QiY/g244cwrS6q
            5YR9yefeTEhg6+i9RK2H9jZ3PYFdiF07jrWc6qnCT7F05eM74MOKjeDHpuHB0k44
            f7mMP9KvJy/tCRIMdrsvxgv5BMRjOh8aTLk6ub52m53z86JScAr3vN9V83Ktkxoq
            akWkBmsAoHDLsVrMjl94kTp0CcUGdlUbAv33w6DNnB+217n9Zt8AwacSTdMhX7F/
            3JsKI3AKqSeSsS9bDV+xC4n62AvAHSvtc6dVnNLGl8JaeGBHLH9OFfZiGQlw0kCm
            /RMhzp+B7ar6AoS6w3MDh7odWzQzgK/f74OCYSxMRY5JiKZuWK7E4XyCj8i+EllD
            y2CH6hCAbkpTStvVheWh7gcnOkccONBMLTzPGcD8Q3/heF67vvOG128lyY+fPjOm
            4LkdJzJaVbSHkIxmxLwHXsOWRCmYflTHEVKsH5h2VPJuYAMLU0MueIN+yC3aF/TS
            XgF2atuWt3GCrx9Nw6t9+BWP5KcZLGCBKrIHswigAdgYivaCdPhF/864ofgWH4PO
            dEjx5nJWx17QTX5k5bzVFmpaivK3V+YHxY6EYsUERvYX6O0FKUiDszDfyJ6oWgo=
            =zcdR
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
