# Von scripts/secret.sh erzeugt. Anwenden mit:
#   sops -d secrets/paperless-secrets.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
type: Opaque
stringData:
    SCW_BUCKET: ENC[AES256_GCM,data:fEfo5AQyJne0n+Y=,iv:lc7nWUus2Y6nWFByTp5+1JrIyVr7YQrQixXVi5SDhz8=,tag:K5L2ftJFuRn6dbWeUT6p9Q==,type:str]
    PAPERLESS_EMAIL_HOST_USER: ENC[AES256_GCM,data:0ob8ec6blwU16lmi58IQ5hJc,iv:iWLI72gJOnRp0qYHv84wONV3sdqjvqZ/RHczcbvoWzE=,tag:xF+BTyJZpgDeHehNwkbMLA==,type:str]
    RCLONE_CONFIG_SCW_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:KtI1kNmgBCwQ4TOvK9xUphocQlCOIXgw+9FJ15fSSIUcob/H,iv:hZo13sg5JE8rXAfKLoZPePx0WoJ3IwKZmCvnVY9fU+U=,tag:alzOX6lcuiuItS0lXDgoCA==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:G1kwy3hY8G0MXN+LGOSxeWpZvEZ4PlP2im2XR93OV293kED6aqZY1R1nsl6Evqq8,iv:5XUX0NhN6d42IDPUZLdJZO1iH7AagytXBXURAV2ZSeU=,tag:HX79rzEiLltA2WGKmqCqEQ==,type:str]
    RCLONE_CONFIG_SCW_ACCESS_KEY_ID: ENC[AES256_GCM,data:QHk923WQpwZOj0sW09A7CL8NiOE=,iv:5ind/371K89pe3lKBpPCkOonLbuZeyQKvDWoQkRZNqE=,tag:Uyw6vfwPuRVjOV2p7CFZEA==,type:str]
    PAPERLESS_EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:CipShpzVIkQvOeIOV4pfm6rPYL+4eHJ0zot2czz/2iw=,iv:gHq/t/3R4/Gg3lNkYsF2Qt/AXKaGkK2xkKh5RxSKgik=,tag:5LHVApZotXwlLKJNxM6g+g==,type:str]
sops:
    lastmodified: "2026-09-06T15:38:13Z"
    mac: ENC[AES256_GCM,data:LEUn27OB00S6vyLmbQBAjdiNRYe3ROawb1FslSS8NmdCwTqhGTLtNVOfH+rIsJUm6OOnkzhIVbRyNHGewkTKU0cfO5sNXxEWVZDYO4tjxKPNvQscOKcyvFAN3ge0PJdA0obajGJL1mmV06bOn07guUKYIATPS3JeJg0eG7Bln5Y=,iv:pqY/AeA6qnHqb1hH+BZcyofmWat36Eo96WBqZ04eKwk=,tag:6XZ4wiDIX1XqEgryoBXw+Q==,type:str]
    pgp:
        - created_at: "2026-09-06T15:38:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPAQ//eqfWXUB8vFdBLqRSxUbxnGRaoNgVTkQ/5ROSH4RnjybJ
            5ty2/jyCXZAOa4pkpJq6naNLkTtecKHAp8F0aJZQbu1jrYocG8lj3pcZxD2IJFvG
            MDswJXgVsSnlRjHFkGtGQ1nsFw8/oal5KydcEVm2MCSsvJBbWKXB0b/CzqxmFDKC
            T5OL6iLOShWivivo6ZuQFYXEEqCKHQ0VJXq07LwWJCaEqiNEfV6j7iWBeHs+l3B9
            S6ItLDk3Di1I2jXoBmjcF63LjezlMn/fvs8hYontmYlN5eNhtV4U2p21dlGjicor
            RkcAj8+xcgEqrKznd1gwJWABZNuNeHbJsMKBt/ci8UW4Q5W/+QRhVKdzII2Hz7Bu
            lKq9UYT44XdfuPEPkjkzbdA84rsvQc+o8xUdSrwwa10lJ9IsImr/3nQ39e98l+pU
            5+Iup71jZIXbuulgUg9bb85RCXWCa2QkkrRt8KSKSU9jmZD0XaduXHNbwNPHLwLP
            m1BC5q7IsW0jHkkhxkcY0CxPY56+GtYZVWkS4gQkenCMUjm3uRdMdzcHts9oSLl4
            JrvD586Cfsd8Tjhp2qY7Vbqm5dMcOg5HrsW3kCZeh8dpBnCEhP16swN9UBub59ek
            rBeyOPXKsaImAOoEfeiyjQE3YMec7K2sZIwSDYi3QhONzMGwGUHVX3Y+8aergE7S
            XgH9f2I+sWcExaX/vRRuSaPoBNBvOxz+d2w28VsWUPE9e2g+CrxKp1nEcsTNHPXn
            gAD1hUPADYoUPaD59fNMLeZmjxz2M4iUFR6h2rEepdB3PI7fMR2fbDycJPyx9Gc=
            =08Lw
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
