# Von tkn pac bootstrap erzeugt, hier gesichert.
# Anwenden mit:
#   sops -d secrets/pipelines-as-code-secret.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: pipelines-as-code-secret
    namespace: pipelines-as-code
type: Opaque
stringData:
    github-application-id: ENC[AES256_GCM,data:HjR5Oi/IoA==,iv:lYIA82lDbKVOB00ZF0P7e+8dNaTZuBPd2gTR9xbucNk=,tag:ZHDQYqRwM36gzEgFtTDBWA==,type:str]
    github-private-key: ENC[AES256_GCM,data:jI6dT3M3OevJvntLKqwSTYAnpvbISdKRKRbDvnxmTALdtEEJuuK/m32EVzlr1ONM3v4Jg3a0wecrep9ShMVG8xj1fdPnJGCzLt3BJH4zzCUlfjVTTDhpy2YKR54FRMWLdsq4ZYS5QFT4FWsjKt0fhBF+wzSW+Jg2cFKsQbPKQYz0c8/RwmcFU4HdBi2DgLbBdXP085Nn0EYWDDJnBG4FzhI55ivvzOSkKv1Pcb77Qs1X6hjGfbI2Bz3qJVXJRrhvjM7IhrED6QOYxuxGfaXbAV9MA2HWkUmxOA+GHnfv0ERgnoGpl/gVz1zo4XB3mAUDEbqwuLjBh3eOtRPwejaBsRbCB2o1eHkSPXmDkVvG96xA8bHYqCVo9nboZvT1KPBJq65d9fi3Da50hAET+J4p5BdFXcH4ADCGvp08m2w8GD5Gi7eSuxz71s7A2lhOyL9E2N2cHHd5Jg7EluKXtW2AINrh8fUgKWjxYTqYJaZuGyWXgYoFRTWBMamGgDL1ItEGzK/mYBhKDU/VkkKecxZCrGiUHpbIpcCWTasfkNI8XieEKrKKwNIwnk6hVD5AwLh4FROHYc61AtI7LVX7Ns+ZvFkqxVf/eiQ3vb2kQD6UG3P5PWS2b1IV8ZGoemjiRYgCXVZ8ufyrBMG9WLQQA7vMbW1zSoRlbTzPiAoTMYiTU2fGM9FvuzukyjQ49536kwI5+VXJT7ake1dqOdm8fdrJ02TxFEyq8yZ74cPuVkYBxhwTgmp+U6BL6Uxv6w1zHLet38Z4bHeDkBgur1CabWjTy1ER2kl99wKpa1HFky5fDQe1q/M7qhsOfRi9pMBknqsLMgyzNG1ctYOcSuH9RVzWQgbHy57KWuSQLANlU8EyluTYkpmoWGx6BnTs0zLCFRmt819QYRg6vh09i8XY00f8OdoBiTvodq202tStHPJdSyGcK1PAggmq2J8mcAEK5i2rYlgcnF9bagAGqRnHK52s4OTI6QSccwfa+aKvzXXzUhFt4/EwgVnj8NAaxf3FeRhlfcQZ0t0KDM4biZOglDhMI43Jqgbkko6HbmS0BTW5BLQnUR30E4ryzsWUXkAyoUBqFYQMZtQNSkkXsal+0Ml8UeUOC05LlOd3vi1kWKDurBlgt2svACMQV9fx/N0yv8MLOh+CdHwbhw5ZC6rayyvIsDCY5K7eb+0nr3pePnbgGNIaUKmym1WZbF3hU2c7U9WD1ThaEg05CVSG0n8hjLwlzGwvnOvN48lwCBoVLwclsinyhWHcm25nZS5yJGy2cYrcVjs4cDSmF51ZDo8gEkSESfgeCsenkELmgn1i0gY6FLjNHN6Cmq4mlaUh2trgtKvHRQBfCUVB27u7iv9kbICMAqUF6Gpr3GKbI28HLKk5cM4hAV0EoMMhjzYdffULOmrjhvnVyg93SXf632/QzrAsAqPH6Il8Q/TqVvSAWRtGWKKlveWIyZrET5rXJ3vjpIn+hAaUBQH0I+4X1DnkLuiUmahEZ7jxuF6zKvWlzMQRUVDUnBve95TvA40XKwa1LiJdLUpEj2f8refH61a34VZbOStLryHrE3sr3Ih5+NTeXyVCLSzdFue6HhCusTBtvQi1HIIQQ6XuyYXmuGChXJCMtS9X+WhrgwTy3YjiJN8J/5vgrIJG6thqNOau4vzSluMjV0vfmmuin0KuaCwKmMow4sdYlpSHiDvtE+/ieeNNwKuVvrQg5R3aJZ4YAoTzl7U7H/p3w98T+fZFPa3sQFnA3zrReoBya+QUcbtuMhqa05jJ4jDuJU/bq6K+QSUDACgiZdoZQksGnNSMkTpDCdPNGET9q+XxoT1hQJHEiAPgS7fMNkDINgjFP10qFvOeLeRNGr7uBjJ3RCvCExvUOjisjfX0b2VQs1mMlczeY8gXHpr10CqQb5k0Yj99nEWewHvBO9viaq/r6nbTdMHeGzdzzenRxB9BjbfE/tSMaAh+sLJc2kCi+pF2sbL92IEzYeVMLZiOWpPHrKGkfvXs41cXjkyogfroKQyRXU7vO27pxyuCwT9ouFVn7maXxXTClPnHIRofOJTKpyQTuLYRNo+08nnJjp8cOjcv8Oq3zQ8fEPCstN+3KPx1UlBvHJU5mFPGPnd6SfAIK595rvv/w+sxVxYtAJTKdgaDLFwYiyDy8HBckC+aNoJb6HZHDdF2QSCBe6auSD9yPXxNS3fFRhfzNS+2DGyizqr6X0eXHtRjg3l/8Pr0JVs2FQH5oyXeemM=,iv:Wvc8pA8X/4m486H8YQUtZ7oQFw4FtbKi7Ya6WbGIy8I=,tag:bH9qBazLNsXJIldud8GWig==,type:str]
    webhook.secret: ENC[AES256_GCM,data:Qpi0q/5LwV9g6zHeXCR6E4sopjTWWER+AmFZ44SzAzfImt1T3iBYuA==,iv:2lnbBaJFT7VVdSjgPAbxOls/YC+b13QT5rEGgh2HJHk=,tag:mRGOUz8yOQWYNmMm9xQIpQ==,type:str]
sops:
    lastmodified: "2026-09-06T11:24:51Z"
    mac: ENC[AES256_GCM,data:OHDz+wXcpAa3M7p62NnJmp9Bivx3XrYV/n1WaUBBv/Pa9jZGTZt3sO9NGEqsMUkiQA8xkqn1NltA1byfpSsg1VPbJ5QAHcTHuF5GkzzXgy6qi921Z+lWpBkJqVCua+N6OQpEJmXkcmGvbWazQjXk7y2rjrY2+IFPtzPWCli6arI=,iv:ZYw6704qyanqsRhoNKJxraAdecAxlcZmbUyJmuvErnQ=,tag:+WS5Q8nk5lQfnxD/IMn4DQ==,type:str]
    pgp:
        - created_at: "2026-09-06T11:24:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPAQ/9GWe2p/rkeye8t5mrfFmbIJ0XcsuUF0QMEBLJ9XGRqN4i
            En8Wpq9FflFlWxywpydBaIZas4c6VB82ldIuO0bg/weKHbAXrl/7ixu1RCjz4CK9
            nbdIoXLPj58HPwTQDQaof9qxqJH/LDbWwBZLPChff9sEMd64Cz8tTNdEJjk+0/EW
            +2E/VcWw1wEncGApk9gk+dD600wLoEjKayIoRzIbY3+Z7kzqnOx3UOJVEIQK93mX
            rt1Qes58HezX04PqK33BDQzSzmEVyUYJZEIaQiPpHfZvwRoUhSM1bAku/R/GCAGQ
            7lRC0IB37Y+YmrxsFfFcYvv7YfGedFcH+UHqaiP6RDkXH/sMYA4QBa2NwlOMrI/K
            2Idm/TB9vyOjTMtfWn5f+5l0i7b8ObaUxd1cOAX3wUt9JGRZEmiCFsYN6HA94c7z
            Y3tD3nDo4+Y03ChRt0WSir/83MEXdIL/zykQZnbekivSuCwlC7ZftZu5IExkXpXo
            8Wa0q8ToRB56u7WpBO4iT6UxiqaFEIhFxEBShZpQuAb32rXezL86jKYjUSBsr8Xi
            f8y8FxFu0EruVZwRT3nKQSxQojgaWMa8wkP29tMqt4aDxyEX83AtYwgznSi1b3ST
            JB+YLG343nn0ICmPnu8CMsoXyB0BVot5Gpum2fWNkc+jlBivyBcYpd+vCLvA/RrS
            XAE78p0PB4tjzMuCfGhxT8z7Na32wR9DBZhTJpNAcWnc9hEyQAhYtwuWjA0PyMyP
            zs7sBOLpIcrZwnhWJVFeQUQFdWntTAXLM4zHbqPcsjUIh/9FpcLKlpz9WyvS
            =StVA
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
