apiVersion: v1
kind: Secret
metadata:
    name: taktwerk-preview-secrets
    namespace: preview-secrets
type: Opaque
data:
    SECRET_KEY: ENC[AES256_GCM,data:7uKAG45pjqSaYpf52VJCdxbHyDA/MUU/k9C0XY9bsKXpI66zFLfDP6k4XtvQGeKbUtB23bcOB3BdBamXGa4vY6IMUxPtqVO9HYTwmyKJtd+VtPmP9VtvJ9Lqsfw=,iv:tbJWSSfgNKQCD1jMzuUljTQMUyhetRt1hz5aDF2yDUg=,tag:6LH6YGjqYNLM2fAG43rYhg==,type:str]
    METRICS_TOKEN: ENC[AES256_GCM,data:I1mD0QdDaSnHcmPeF7kSlzNIXUD24qywmpDUq5V3Oh/e916PbLr23edoN4ran3vdfG4AkHHKlog9guo9,iv:aQpo+NxRfgWlVbUCR4DI/5IeL/q8CPaGYYA8EFPNeNQ=,tag:Roxla0lEPgg+yrWF/yjkig==,type:str]
    TELEMETRY_SALT: ENC[AES256_GCM,data:pcwMQ2UuQx5rCcqpFxRTFiRfMby2kkdGMpm65SJYrgpFJTb+G0htjah3XX/f7URgfSz2D7662dklmbtP,iv:7WtAE8ZwpqoaqskmZBe6Nuh29s35oy13yHMGSQP/zlQ=,tag:w9HxejLRHPaxZSngdernvg==,type:str]
    SEED_ADMIN_PASSWORD: ENC[AES256_GCM,data:8GDyXo7LSvGjyynMQo1Upi7zBjA5XIF6ksflzAlLsjQ=,iv:OWGYlkp7iiEFAXVBw6F9j3XGm1oDa2/xrALK40kiME8=,tag:k2FRGCGl9d7tmhtg1REnpA==,type:str]
    SEED_MEMBER_PASSWORD: ENC[AES256_GCM,data:sf7bpVtw36CK8SHmNQYVB/j8XKTbdSQLzYzfJ/dFCR0=,iv:OLrqW1OEqk+Xwt49BIuMbtywDkK1G2+7kXyLyGlpr18=,tag:pOtkgKaxqTWdFsng/uZpXA==,type:str]
sops:
    lastmodified: "2026-09-20T14:23:05Z"
    mac: ENC[AES256_GCM,data:aJxKSrff0j9XGXOYfLoWW7Ehj6Wf4Ag+45ayxRQGl6iif61UvcZSSyQSkwD475m3ciz+pA1eH6u1dTybl2XN9ZBgKD1JLGiwpfkT6Oa7TzsTV5qON0EA2qfDHjPyR/rcfsrCmcHXyf75PE7lzf+ZnxHjCvhGlNUdfrmdzgj1V6U=,iv:0obV5voC5nnJCUlODyjhF5Vm1iU3Fp4NLGF97XlLbhU=,tag:339AhuM8Ii59yjdi2Lws7w==,type:str]
    pgp:
        - created_at: "2026-09-20T14:23:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPAQ/9G1JWeOeimtFWMYqc/vEoSUGs5vWqQvyeaLJyzYX1bbuX
            PmgEWWMJ3Bw5MsGkgIqb2t0RAekTR96+ZHtHfUr8fH0PEpfYuX6ZmiBhtusg8r1t
            Hc51chj4832byrNovMunft+8O5qFjF3jpnEDXTcp2LKxdYEZQ8fOsVub2ZrV5e/o
            wMU9g1etLOwrugrD31wTW/UXfJ/bNfeVPg4Fn4tWIuEMYxTtk/CBLuW+ojd2hMnI
            tTnAkH4wTXa/kh1/5E7zGCa9fG8u1quJX1nuoSw7hoDBOMdCztJNCcFgqnkonyFt
            e7Qe86fl8JjgSmMHs/YtBV2FfJ9WtMmUDX7Pr3Ft/8A7eCJmlhC0LbOof/D+k4uz
            kpbN2rADHPZq1lGuplJMvuuwwfMTSUBSil6qNGme2/WWZi4nsFyW3pfqdPsXaHM2
            NBiDsqOPg0U6rP5YAv9SqHOy3lFBQ1UaUpCR8wVLbUZEbIGTNa0eNExXd/o6mKZH
            OSgystBSUDwuk0+fu8gJbIT/nLqbxdvH2N+/9mLqyGmzbmRP3apVCrpXXppxJ5Gn
            0t5C/zaOmIFJe8pPFuCO5+a+aLvrH3ksd9vbJJFamZp2dDGnxoXGEtBdbSO6YRYq
            W7igmtld4O86TREFI1F4qdx0qoTZdAxIA0CVZJ3V3+1iVC+7GRZLx+Obm/XhdOLS
            XgEM2tyt9l2KmstW0IsOrbMVOklrNzAd2VOk0o+XNDEgncrMYTwzYDEKhj6SpNFe
            ArvxICWKfMn0xdQ9uV9e1deZjX90bIEhSgxDYvwOB31LErEAqq/UtgNYE1RYcKM=
            =U6kc
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
