# Von scripts/secret.sh erzeugt. Anwenden mit:
#   sops -d secrets/umami-secrets.sops.yaml | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
    name: umami-secrets
    namespace: umami
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:y2PUQgy1iRv0aJ6/xF8ZaxCZIsgNGFOa981hnuMlldg=,iv:45KsTRTm77Guo+bopKXuBnhaGUOmxdclVTI2yTXn+WQ=,tag:FGfGT8fQdlzoHaVSlwj82w==,type:str]
    app-secret: ENC[AES256_GCM,data:PxfLCf5HcSLpdYTefVDNRTWsUwbBn1IUp7A7ocp1bAZbeckXLsLycR3sxxPZ1z13RkI=,iv:lGhM5qKuusCDCSt6k47r6WywGaCp6GoAhXcmULhQyMQ=,tag:dBDqIsXX5eyT8nWCYqzLRw==,type:str]
    two-factor-encryption-key: ENC[AES256_GCM,data:png1qPlg09zzw8dSU/hUU0dmYbNOZ0rejffkscFYwHQEUTYKsq97k+2lV7o+XXkWGYaoUgqib/aG80H9+dOuGg==,iv:FU+cHoOkOCEdTrm32Vve4zNfXQ8pp72IGW/XOxawxTo=,tag:LJVcIIDtAIRcY5gYHQbRpQ==,type:str]
sops:
    lastmodified: "2026-09-15T23:08:21Z"
    mac: ENC[AES256_GCM,data:jhY8Bzd3JUCNPYbPTuQdGz5tistRukVCJklNNgw/LoqRL73RiVXY5uucAyn1PMQAi3YFvZuISa0tFbWYZALpcWhjknK3uptspXsEYspd9vgvzSIzQVy0UgTp1LXC131A4MXVyBo1E2ESrrBzYfNIDU6LQWW5t4KGGv2OQtZZGLw=,iv:E6U6OKDu2IF6xDU8ujjGnw/rOusVBiHRc51GWV1wCL8=,tag:5bo5K3liR68+JwAK2jfysg==,type:str]
    pgp:
        - created_at: "2026-09-15T23:08:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8g2TDuKJOPPARAAnoA/YSI0LiWvVdzbD9vqWngYFQ0f3krO5qtLJVZvqRjf
            sIpTd8UVqIVU/LWzEz/loJnBgiphdmdMU0zPhIuZeYpZoZmEevG1AM6mt4qr2S2c
            1WQNsxvZnCbxK78xGerLoLYvfDcRsjVAY3WvV3pkINddm+1KxP8Ze/OmuEr41KWF
            ZbWK1L+zRH0SaRYr71/KFOPF1Sb3H2SExhJy4QxI0+G02afI2tsbqu1k4nsqa6n0
            1OtzjKqqk3QcB0sK9xniB/okBpALNdl4dIVWmXsKFYReZoG2HxNilXGigtyM/Ruc
            5To6xoOnEZf8wUVLsSW0qwIstH6sANdxAO6RfBTflfuEB4dEahwbyW+B6kswsBKk
            2LqogGxbDVIppvhFzQ9IjOdGT0ApOPUtNSr7leeCO0ZaTYtkjS1ev2OltbBcc2uW
            fG2qrvNgxpbbpZT9OyKCdQYxMM6Tg0x7cN+ZiQFExtK3K2Kh3HTwSQ1y88TxVICR
            IHXgpJzuAtNzHJUtxUO4fLA4VKZBXYhlu0jKQf+8DmOF3vPZpSyURoorEMf5UN+Z
            mxR38dw3Pbs/5icSh062gy+mg+7eBaDwz20zgT101EirtpasHhWGA93DSSUmRdeG
            UVC0/pGlb8xXdEN+UTDmT7mU780DAkCNxGpTqGOi98vAlPUesEvawvPGAMLT7cvS
            XgHFmkMqUa3VxqfrQMZdwV8V0oV5kw9SIXqXuNbnwyTlff6UlXJiO8ed22fDP3QQ
            QVJW0X99n4ivXoNfZJJcTsXrfOGqehR33tq+Wnd1VVvqTLv3btJS48LiB9aV8Vg=
            =Qrn6
            -----END PGP MESSAGE-----
          fp: 7954EC02CDDF896536DFDCDE056C6FDDF9E15CF2
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
